@startuml "Model"


entity Movie{
    +Id : int 
    + Title : string
    +Link : string
    + Rating : Rating
}
entity User{

    +Id : int
    +Name : string
    +Email : string
    +Password : string
    + Admin : bool
   
}

entity Genre{

+ Id : int
+ Name : string

}

entity Rating{
+ Id : int
+Grade : int

}

@enduml